### ISSUE TITLE
There is a "missed" tag in widgets2016.html and it's confused

### ISSUE THREAD

**Issue by winhows5** [aparrish/dmep-python-intro#2]
Professor, I'm a student in your Shenzhen class.I'm working on web-scraping-worksheet  and that confused me, the expression  `html_str.find('table', attrs={'class': 'widgetlist'}).find('tbody')` returns `None`. 
I looked up the source code and found there isn't a tag \<tbody>, while there is \<tbody> in `Elements`.
Could you please explain why this happened? Thx
`<table class="widgetlist">`
`	<thead>`
`		<td>Part No.</td>`
`		<td>Name</td>`
`		<td>Price</td>`
`		<td>Quantity in warehouse</td>`
`	</thead>`
`  <tr class="winfo">`
`  </tr>`
`</table>`

You can email me by wangwenhao5@foxmail.com if needed.

**Comment by aparrish** [comment]
Hi! You're right that there's no `<tbody>` tag in the original source. Where are you seeing a reference to `<tbody>`? (I'm not sure what you mean by "there is <tbody> in `Elements`".)

**Comment by winhows5** [comment]
<img width="272" alt="screenshot" src="https://user-images.githubusercontent.com/20163093/28511948-3895f54c-7082-11e7-92b0-0fb6a610f185.png">
Developer Tools -> Elements: 'tbody' exists;

Developer Tools -> Sources: 'tbody' doesn't exist;

I upload a picture to explain. Hope it's clear enough  :D

**Comment by aparrish** [comment]
Ah, okay! I see what you mean now, thank you for clarifying. Here's what's happening (I think). According to the official standard, tables are supposed to have `<tbody>` tags—you use `<thead>` for the table header row, and `<tbody>` for the remaining rows (the "body" of the table). I'm a sloppy HTML coder and forgot to include the `<tbody>`, so the browser just assumed that I had *meant* to include it, and automatically included it in its internal representation of how the page is structured. This is confusing, because it means that the version of the page in the inspector isn't always the same thing as the version of the page in the code itself (and Beautiful Soup's idea of the page might be different as well). Unfortunately, this is just a side-effect of the fact that browsers are very lenient in how they parse HTML. When in doubt, trust the source code over what you see in the web inspector.

**Comment by winhows5** [comment]
Get it!
thank you Professor😸
